name: zakat_calculator
description: A comprehensive Zakat calculator based on Hanafi school
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.1
  shared_preferences: ^2.2.2
  http: ^1.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  intl: ^0.20.2
  connectivity_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_main"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/